version: "3.11"

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: awesomeshop-services-payments-api
    restart: unless-stopped
    networks:
      - mcourse
    ports:
      - 5004:5004
    environment:
      ASPNETCORE_URLS: "http://+:5004"
      ASPNETCORE_ENVIRONMENT: "Development"

networks:
  mcourse:
    name: mcourse
  